export function getNotesElements() {
  return {
    notesHome: document.querySelector("#notes-home"),
    notesReader: document.querySelector("#notes-reader"),
    notesEditor: document.querySelector("#notes-editor"),
    newNoteButton: document.querySelector("#new-note-button"),
    noteReaderBackButton: document.querySelector("#note-reader-back"),
    noteReaderEditButton: document.querySelector("#note-reader-edit"),
    noteReaderDeleteButton: document.querySelector("#note-reader-delete"),
    noteReaderTitle: document.querySelector("#note-reader-title"),
    noteReaderMeta: document.querySelector("#note-reader-meta"),
    noteReaderAsset: document.querySelector("#note-reader-asset"),
    noteReaderContent: document.querySelector("#note-reader-content"),
    noteBackButton: document.querySelector("#note-back-button"),
    noteSaveDraftButton: document.querySelector("#note-save-draft"),
    noteForm: document.querySelector("#note-form"),
    notesSearch: document.querySelector("#notes-search"),
    notesMeta: document.querySelector("#notes-meta"),
    noteFilterTags: document.querySelector("#note-filter-tags"),
    noteTitleCount: document.querySelector("#note-title-count"),
    noteContentCount: document.querySelector("#note-content-count"),
    noteTemplateCards: document.querySelector("#note-template-cards"),
    noteNewTagButton: document.querySelector("#note-new-tag-button"),
    noteCustomTagField: document.querySelector("#note-custom-tag-field"),
    noteAssetSelect: document.querySelector("#note-asset-select"),
    noteTransactionSelect: document.querySelector("#note-transaction-select"),
    noteSuggestedTransactions: document.querySelector("#note-suggested-transactions"),
    notesList: document.querySelector("#notes-list"),
    closeReviewModal: document.querySelector("#close-review-modal"),
    closeReviewMessage: document.querySelector("#close-review-message"),
    closeReviewLater: document.querySelector("#close-review-later"),
    closeReviewWrite: document.querySelector("#close-review-write")
  };
}
