export function getSettingsElements() {
  return {
    settingsButton: document.querySelector("#settings-button"),
    settingsPanel: document.querySelector("#settings-panel"),
    authButton: document.querySelector("#auth-button"),
    authPanel: document.querySelector("#auth-panel"),
    authUserMenu: document.querySelector("#auth-user-menu"),
    authCloseButton: document.querySelector("#auth-close-button"),
    authEmail: document.querySelector("#auth-email"),
    authPassword: document.querySelector("#auth-password"),
    authPasswordToggle: document.querySelector("#auth-password-toggle"),
    authName: document.querySelector("#auth-name"),
    authNameField: document.querySelector("#auth-name-field"),
    authSubmitButton: document.querySelector("#auth-submit-button"),
    authModeToggle: document.querySelector("#auth-mode-toggle"),
    authSwitchCopy: document.querySelector("#auth-switch-copy"),
    authIntro: document.querySelector("#auth-intro"),
    authResetButton: document.querySelector("#auth-reset-button"),
    authProviderButtons: document.querySelectorAll("[data-auth-provider]"),
    authStatus: document.querySelector("#auth-status"),
    authLogoutButton: document.querySelector("#auth-logout-button"),
    settingCurrency: document.querySelector("#setting-currency"),
    settingUsdCnyRate: document.querySelector("#setting-usd-cny-rate"),
    settingBtcUsdRate: document.querySelector("#setting-btc-usd-rate"),
    settingUsdHkdRate: document.querySelector("#setting-usd-hkd-rate"),
    settingLanguage: document.querySelector("#setting-language"),
    settingFont: document.querySelector("#setting-font"),
    settingTheme: document.querySelector("#setting-theme"),
    resetDemo: document.querySelector("#reset-demo")
  };
}
