export const demoState = {
  session: {
    signedIn: true,
    email: "demo@asset-trail.local",
    name: "本地用户",
    signedInAt: "2026-04-28T00:00:00.000Z"
  },
  settings: {
    displayCurrency: "CNY",
    usdCnyRate: "6.85",
    btcUsdRate: "70000",
    usdHkdRate: "7.82",
    language: "zh",
    font: "rounded",
    theme: "light"
  },
  selectedAccount: "all",
  snapshots: [
    { date: "2025-04-28", valueCents: "14600000" },
    { date: "2025-07-28", valueCents: "15120000" },
    { date: "2025-10-28", valueCents: "18100000" },
    { date: "2026-01-28", valueCents: "23900000" },
    { date: "2026-04-28", valueCents: "29160000" }
  ],
  assets: [
    {
      id: "demo-sp500",
      name: "标普500 ETF",
      symbol: "SPY",
      type: "基金",
      account: "长期账户",
      accountType: "long_term",
      currency: "USD",
      quantity: "180",
      costPrice: "500.00",
      previousPrice: "512.00",
      currentPrice: "520.00",
      fxRate: "1",
      previousFxRate: "1",
      contribution: "0",
      dividends: "0",
      interest: "0",
      fees: "12.00",
      taxes: "0",
      manualAdjustment: "0",
      transactionType: "买入",
      priceSource: "EODHD 模拟",
      pricedAt: "2026-04-28",
      attachmentName: "demo-us-etf.csv",
      buyReason: "作为全球权益底仓，覆盖美国大盘企业盈利增长。",
      upsideReasons: "盈利韧性\n降息预期\n长期指数化配置",
      downsideReasons: "估值偏高\n美元流动性收紧\n经济增长放缓",
      purchaseDate: "2025-04-28",
      trendReturnBps: "400",
      updatedAt: "2026-04-28T00:00:00.000Z"
    },
    {
      id: "demo-nvda",
      name: "英伟达",
      symbol: "NVDA",
      type: "股票",
      account: "成长账户",
      accountType: "securities",
      currency: "USD",
      quantity: "65",
      costPrice: "900.00",
      previousPrice: "890.00",
      currentPrice: "880.00",
      fxRate: "1",
      previousFxRate: "1",
      contribution: "0",
      dividends: "0",
      interest: "0",
      fees: "8.00",
      taxes: "0",
      manualAdjustment: "0",
      transactionType: "买入",
      priceSource: "Polygon 模拟",
      pricedAt: "2026-04-28",
      attachmentName: "",
      buyReason: "保留 AI 算力产业链核心资产敞口，但控制单一股票仓位。",
      upsideReasons: "数据中心需求延续\n毛利率保持高位\n新产品周期放量",
      downsideReasons: "估值消化压力\n客户资本开支放缓\n竞争加剧",
      purchaseDate: "2026-01-28",
      trendReturnBps: "-220",
      updatedAt: "2026-04-28T00:00:00.000Z"
    },
    {
      id: "demo-kweb",
      name: "中概互联 ETF",
      symbol: "513050",
      type: "基金",
      account: "长期账户",
      accountType: "long_term",
      currency: "CNY",
      quantity: "160000",
      costPrice: "1.50",
      previousPrice: "1.48",
      currentPrice: "1.45",
      fxRate: "0.1460",
      previousFxRate: "0.1455",
      contribution: "0",
      dividends: "0",
      interest: "0",
      fees: "28.00",
      taxes: "0",
      manualAdjustment: "0",
      transactionType: "买入",
      priceSource: "Tushare fund_daily 模拟",
      pricedAt: "2026-04-28",
      attachmentName: "",
      buyReason: "配置低估值互联网平台资产，作为中国权益的弹性仓位。",
      upsideReasons: "估值修复\n回购提升股东回报\n平台盈利改善",
      downsideReasons: "政策不确定性\n消费恢复偏慢\n海外上市情绪波动",
      purchaseDate: "2025-10-28",
      trendReturnBps: "-330",
      updatedAt: "2026-04-28T00:00:00.000Z"
    },
    {
      id: "demo-btc",
      name: "比特币现货",
      symbol: "BTC",
      type: "数字资产",
      account: "加密货币账户",
      accountType: "crypto",
      currency: "USD",
      quantity: "0.8",
      costPrice: "70000.00",
      previousPrice: "71800.00",
      currentPrice: "73500.00",
      fxRate: "1",
      previousFxRate: "1",
      contribution: "0",
      dividends: "0",
      interest: "0",
      fees: "3.00",
      taxes: "0",
      manualAdjustment: "0",
      transactionType: "买入",
      priceSource: "用户录入",
      pricedAt: "2026-04-28",
      attachmentName: "",
      buyReason: "小比例配置高波动资产，观察其与传统资产的相关性。",
      upsideReasons: "供给稀缺叙事\n机构配置增加\n美元流动性改善",
      downsideReasons: "监管扰动\n高波动止损压力\n风险资产同步回撤",
      purchaseDate: "2025-04-28",
      trendReturnBps: "500",
      updatedAt: "2026-04-28T00:00:00.000Z"
    },
    {
      id: "demo-cash",
      name: "现金备用金",
      type: "现金",
      account: "备用金",
      accountType: "cash",
      currency: "CNY",
      quantity: "330000",
      costPrice: "1.00",
      previousPrice: "1.00",
      currentPrice: "1.00",
      fxRate: "0.1460",
      previousFxRate: "0.1460",
      contribution: "0",
      dividends: "0",
      interest: "0",
      fees: "0",
      taxes: "0",
      manualAdjustment: "0",
      transactionType: "转入",
      priceSource: "用户录入",
      pricedAt: "2026-04-28",
      attachmentName: "",
      buyReason: "保留流动性，用于应对回撤后的再平衡。",
      upsideReasons: "等待买点\n降低波动\n满足短期开支",
      downsideReasons: "通胀侵蚀\n机会成本\n收益率偏低",
      purchaseDate: "2026-03-28",
      trendReturnBps: "0",
      updatedAt: "2026-04-28T00:00:00.000Z"
    }
  ],
  notes: [
    {
      id: "note-demo-1",
      title: "纳指回调时的心态复盘",
      asset: "买入 纳指ETF",
      tags: ["复盘", "交易心理"],
      format: "plain",
      status: "published",
      content: "今天市场回调幅度不小，盘中一度感到焦虑，差点减仓。\n\n复盘后发现，问题不在逻辑，而在预期管理。需要把波动范围和仓位纪律提前写清楚。",
      createdAt: "2026-05-29T21:42:00.000Z"
    },
    {
      id: "note-demo-2",
      title: "长期投资的核心是时间复利",
      asset: "",
      tags: ["理财学习", "原则"],
      format: "plain",
      status: "published",
      content: "复利不是靠收益率堆出来的，而是靠时间和纪律。\n\n尽量减少不必要的操作，让时间成为朋友。",
      createdAt: "2026-05-28T15:18:00.000Z"
    },
    {
      id: "note-demo-3",
      title: "关于分散投资的一点思考",
      asset: "",
      tags: ["复盘"],
      format: "plain",
      status: "published",
      content: "分散的本质是降低非系统性风险，而不是无脑持有更多标的。\n\n核心在于相关性、行业周期、估值分位和资金分配效率。",
      createdAt: "2026-05-27T10:07:00.000Z"
    }
  ],
  posts: [
    {
      id: "post-demo",
      title: "多币种资产记录时先统一基准币",
      tag: "数据质量",
      content: "记录原始币种和折算汇率时间戳，后续分析会更容易解释。",
      status: "已发布",
      reports: 0,
      createdAt: "2026-04-28T00:00:00.000Z"
    }
  ]
};
